### ISSUE TITLE
system-filepath dropped?

### ISSUE THREAD

**Issue by gibiansky** [snoyberg/classy-prelude#102]
Why was `system-filepath` dropped?

This caused some easy-to-fix build failures but mostly I'm curious as to the reasoning. I always liked having `FilePath` be distinct from `String` and having the difference be enforced by the type system, so am curious as to why it's been removed / deprecated.

**Comment by gregwebs** [comment]
I am curious to know also. Personally I have been questioning whether the extra overhead of system-filepath is worth it for a lot of use cases. If you control your filepath names then it doesn't add a lot of value. The real value is if you want to handle an arbitrary file path.

In the future it would be better to make a change like this with a pull request. That way those like myself that are watching the repo activity that don't get notified about every commit will see the change.

**Comment by snoyberg** [comment]
Apologies from my side, I should have discussed this earlier. The reason here is:

* The original author of system-filepath stopped supporting it a few months back
* We at FP Complete took over maintenance
* After quite a bit of wasted effort, we came to the conclusion that the code base was unsalvageable, so we similarly decided to deprecate it

But I shouldn't have made these moves so quickly and without discussing them first, that was just born out of frustration with having wasted so much time on the problem already. I'll put up a blog post on the deprecation on yesodweb.com so others hear about it.

**Comment by snoyberg** [comment]
Here's the draft of a blog post on this:

https://github.com/yesodweb/yesodweb.com-content/blob/master/blog/2015/05/deprecating-system-filepath.md

Just waiting to hear back from a coworker on one point before publishing.
